### ISSUE TITLE
'kotlin-android-extensions' Gradle plugin is no longer supported

### ISSUE THREAD

**Issue by edapess** [socure-inc/socure-sigmadevice-wrapper-react-native#3]
It turns out that this package uses depracated `kotlin-android-extensions`, will you update this in the near future?

**Comment by rburunkayaSocure** [comment]
Hi @edapess 

Thanks for reaching out us. We are going to update it in next releases but currently for supporting older version of Kotlin as well, we are still keeping it in place. We are going to notify you when we have an update in future.

Kind regards

**Comment by edapess** [comment]
Hi @rburunkayaSocure,

 is there any updates on this issue?

**Comment by rburunkayaSocure** [comment]
Hi @edapess,

We did not release new Device SDKs yet to address this issue but it is in our road map. I am going to notify you when we release the new Device SDKs.

Kind regards

**Comment by abgaryanharutyun** [comment]
Hey @rburunkayaSocure can we have timing about this?

**Comment by abgaryanharutyun** [comment]
@rburunkayaSocure do we have any update here?

**Comment by rburunkayaSocure** [comment]
Hi @abgaryanharutyun 

Sorry about delayed SDK arrivals. We are planning to release Device SDKs 4.x in next couple of weeks. I am going to provide an update as soon as SDKs released.

Kind regards,

**Comment by williecoo96** [comment]
Hello @rburunkayaSocure - just wanted to circle back on this. Do you have any update on the status of the new Device SDK release? We are hoping to release an Android version of our app ASAP and as of now Socure (inability to connect) is our primary blocker.

**Comment by rburunkayaSocure** [comment]
Hey @williecoo96 

Tentatively we are targeting to release on February 12. Once it is confirmed I will keep you posted. 

Kind regards,

**Comment by williecoo96** [comment]
Hey @rburunkayaSocure - Just circling back here. Was this released on Monday? How are things looking?

**Comment by rburunkayaSocure** [comment]
Hey @williecoo96 

We released the Sigma React-Native wrapper.

Kind regards,
